In [9]:
import pandas as pd
df=pd.read_csv("indian_roads_dataset.csv")
print(df.head())

   accident_id        city        state   latitude  longitude        date  \
0            0        Pune  Maharashtra  18.680827  73.930388  22-10-2023
1            1      Mumbai  Maharashtra  18.817732  72.790846  21-05-2023
2            2      Mumbai  Maharashtra  19.096889  72.819424  10-07-2024
3            3  Chandigarh       Punjab  30.787805  76.847507  30-03-2025
4            4     Chennai   Tamil Nadu  12.965155  80.283313  25-01-2024

    time  hour day_of_week  is_weekend  ... visibility  temperature  \
0  05:00     5      Sunday           1  ...        low           32
1  04:00     4      Sunday           1  ...       high           34
2  13:00    13   Wednesday           0  ...        low           21
3  11:00    11      Sunday           1  ...        low           30
4  16:00    16    Thursday           0  ...       high           24

   traffic_density        cause accident_severity  vehicles_involved  \
0             high      weather             fatal                  2
1              low      weather             major                  4
2           medium      weather             minor                  1
3             high  distraction             minor                  5
4              low  distraction             minor                  2

  casualties is_peak_hour festival  risk_score
0          2            0      NaN        0.85
1          3            0      NaN        0.10
2          1            0      NaN        0.45
3          2            0      NaN        0.65
4          1            0      NaN        0.10

[5 rows x 24 columns]

In [11]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   accident_id        20000 non-null  int64
 1   city               20000 non-null  object
 2   state              20000 non-null  object
 3   latitude           20000 non-null  float64
 4   longitude          20000 non-null  float64
 5   date               20000 non-null  object
 6   time               20000 non-null  object
 7   hour               20000 non-null  int64
 8   day_of_week        20000 non-null  object
 9   is_weekend         20000 non-null  int64
 10  road_type          20000 non-null  object
 11  lanes              20000 non-null  int64
 12  traffic_signal     20000 non-null  int64
 13  weather            20000 non-null  object
 14  visibility         20000 non-null  object
 15  temperature        20000 non-null  int64
 16  traffic_density    20000 non-null  object
 17  cause              20000 non-null  object
 18  accident_severity  20000 non-null  object
 19  vehicles_involved  20000 non-null  int64
 20  casualties         20000 non-null  int64
 21  is_peak_hour       20000 non-null  int64
 22  festival           115 non-null    object
 23  risk_score         20000 non-null  float64
dtypes: float64(3), int64(9), object(12)
memory usage: 3.7+ MB
None

In [13]:
print(df.columns)

Index(['accident_id', 'city', 'state', 'latitude', 'longitude', 'date', 'time',
       'hour', 'day_of_week', 'is_weekend', 'road_type', 'lanes',
       'traffic_signal', 'weather', 'visibility', 'temperature',
       'traffic_density', 'cause', 'accident_severity', 'vehicles_involved',
       'casualties', 'is_peak_hour', 'festival', 'risk_score'],
      dtype='object')

In [15]:
print(df.shape)

(20000, 24)

In [17]:
print(df.isnull().sum())

accident_id              0
city                     0
state                    0
latitude                 0
longitude                0
date                     0
time                     0
hour                     0
day_of_week              0
is_weekend               0
road_type                0
lanes                    0
traffic_signal           0
weather                  0
visibility               0
temperature              0
traffic_density          0
cause                    0
accident_severity        0
vehicles_involved        0
casualties               0
is_peak_hour             0
festival             19885
risk_score               0
dtype: int64

In [21]:
print(df.duplicated().sum())

0

In [23]:
df.drop('festival',axis=1,inplace=True)

In [25]:
print(df)

       accident_id        city        state   latitude  longitude        date  \
0                0        Pune  Maharashtra  18.680827  73.930388  22-10-2023
1                1      Mumbai  Maharashtra  18.817732  72.790846  21-05-2023
2                2      Mumbai  Maharashtra  19.096889  72.819424  10-07-2024
3                3  Chandigarh       Punjab  30.787805  76.847507  30-03-2025
4                4     Chennai   Tamil Nadu  12.965155  80.283313  25-01-2024
...            ...         ...          ...        ...        ...         ...
19995        19995   Bangalore    Karnataka  13.092276  77.599571  29-09-2022
19996        19996     Chennai   Tamil Nadu  13.172928  80.157062  25-11-2023
19997        19997     Chennai   Tamil Nadu  12.997170  80.150724  18-06-2022
19998        19998     Kolkata  West Bengal  22.454882  88.322213  12-03-2023
19999        19999       Delhi        Delhi  28.510266  77.065301  05-07-2024

        time  hour day_of_week  is_weekend  ... weather  visibility  \
0      05:00     5      Sunday           1  ...     fog         low
1      04:00     4      Sunday           1  ...   clear        high
2      13:00    13   Wednesday           0  ...     fog         low
3      11:00    11      Sunday           1  ...     fog         low
4      16:00    16    Thursday           0  ...   clear        high
...      ...   ...         ...         ...  ...     ...         ...
19995  03:00     3    Thursday           0  ...   clear        high
19996  01:00     1    Saturday           1  ...   clear        high
19997  15:00    15    Saturday           1  ...   clear        high
19998  04:00     4      Sunday           1  ...   clear        high
19999  23:00    23      Friday           0  ...    rain         low

       temperature traffic_density         cause  accident_severity  \
0               32            high       weather              fatal
1               34             low       weather              major
2               21          medium       weather              minor
3               30            high   distraction              minor
4               24             low   distraction              minor
...            ...             ...           ...                ...
19995           31             low   distraction              minor
19996           20             low   distraction              major
19997           22             low       weather              minor
19998           33             low     poor road              minor
19999           39            high  overspeeding              minor

      vehicles_involved casualties is_peak_hour  risk_score
0                     2          2            0        0.85
1                     4          3            0        0.10
2                     1          1            0        0.45
3                     5          2            0        0.65
4                     2          1            0        0.10
...                 ...        ...          ...         ...
19995                 3          2            0        0.10
19996                 4          2            0        0.10
19997                 3          3            0        0.10
19998                 1          0            0        0.10
19999                 4          2            0        0.65

[20000 rows x 23 columns]

In [27]:
df.drop_duplicates(inplace=True)

In [37]:
df['date']=pd.to_datetime(df['date'],dayfirst=True)

In [39]:
print(df)

       accident_id        city        state   latitude  longitude       date  \
0                0        Pune  Maharashtra  18.680827  73.930388 2023-10-22
1                1      Mumbai  Maharashtra  18.817732  72.790846 2023-05-21
2                2      Mumbai  Maharashtra  19.096889  72.819424 2024-07-10
3                3  Chandigarh       Punjab  30.787805  76.847507 2025-03-30
4                4     Chennai   Tamil Nadu  12.965155  80.283313 2024-01-25
...            ...         ...          ...        ...        ...        ...
19995        19995   Bangalore    Karnataka  13.092276  77.599571 2022-09-29
19996        19996     Chennai   Tamil Nadu  13.172928  80.157062 2023-11-25
19997        19997     Chennai   Tamil Nadu  12.997170  80.150724 2022-06-18
19998        19998     Kolkata  West Bengal  22.454882  88.322213 2023-03-12
19999        19999       Delhi        Delhi  28.510266  77.065301 2024-07-05

        time  hour day_of_week  is_weekend  ... weather  visibility  \
0      05:00     5      Sunday           1  ...     fog         low
1      04:00     4      Sunday           1  ...   clear        high
2      13:00    13   Wednesday           0  ...     fog         low
3      11:00    11      Sunday           1  ...     fog         low
4      16:00    16    Thursday           0  ...   clear        high
...      ...   ...         ...         ...  ...     ...         ...
19995  03:00     3    Thursday           0  ...   clear        high
19996  01:00     1    Saturday           1  ...   clear        high
19997  15:00    15    Saturday           1  ...   clear        high
19998  04:00     4      Sunday           1  ...   clear        high
19999  23:00    23      Friday           0  ...    rain         low

       temperature traffic_density         cause  accident_severity  \
0               32            high       weather              fatal
1               34             low       weather              major
2               21          medium       weather              minor
3               30            high   distraction              minor
4               24             low   distraction              minor
...            ...             ...           ...                ...
19995           31             low   distraction              minor
19996           20             low   distraction              major
19997           22             low       weather              minor
19998           33             low     poor road              minor
19999           39            high  overspeeding              minor

      vehicles_involved casualties is_peak_hour  risk_score
0                     2          2            0        0.85
1                     4          3            0        0.10
2                     1          1            0        0.45
3                     5          2            0        0.65
4                     2          1            0        0.10
...                 ...        ...          ...         ...
19995                 3          2            0        0.10
19996                 4          2            0        0.10
19997                 3          3            0        0.10
19998                 1          0            0        0.10
19999                 4          2            0        0.65

[20000 rows x 23 columns]

In [43]:
print(df.describe())

        accident_id      latitude     longitude  \
count  20000.000000  20000.000000  20000.000000
mean    9999.500000     20.389207     78.173330
min        0.000000     12.800172     72.700017
25%     4999.750000     13.198653     73.997979
50%     9999.500000     18.812008     77.297000
75%    14999.250000     28.402467     80.111089
max    19999.000000     30.799960     88.499861
std     5773.647028      6.165791      4.485967

                                date          hour    is_weekend  \
count                          20000  20000.000000  20000.000000
mean   2023-08-22 07:04:48.000000256     11.487200      0.286150
min              2022-01-01 00:00:00      0.000000      0.000000
25%              2022-10-25 00:00:00      5.000000      0.000000
50%              2023-08-21 00:00:00     12.000000      0.000000
75%              2024-06-21 00:00:00     18.000000      1.000000
max              2025-04-15 00:00:00     23.000000      1.000000
std                              NaN      6.945563      0.451972

              lanes  traffic_signal   temperature  vehicles_involved  \
count  20000.000000    20000.000000  20000.000000       20000.000000
mean       3.493950        0.499850     27.579600           2.992000
min        1.000000        0.000000     15.000000           1.000000
25%        2.000000        0.000000     21.000000           2.000000
50%        4.000000        0.000000     28.000000           3.000000
75%        5.000000        1.000000     34.000000           4.000000
max        6.000000        1.000000     40.000000           5.000000
std        1.705406        0.500012      7.454746           1.415534

         casualties  is_peak_hour    risk_score
count  20000.000000  20000.000000  20000.000000
mean       1.726450      0.247400      0.437585
min        0.000000      0.000000      0.100000
25%        1.000000      0.000000      0.250000
50%        1.000000      0.000000      0.450000
75%        3.000000      0.000000      0.600000
max        5.000000      1.000000      1.000000
std        1.489104      0.431512      0.218130

In [47]:
df['accident_severity'].value_counts()

cause
distraction      4026
overspeeding     4025
weather          3997
drunk driving    3978
poor road        3974
Name: count, dtype: int64

In [49]:
df['weather'].value_counts()

weather
clear    6690
rain     6677
fog      6633
Name: count, dtype: int64

In [51]:

df['road_type'].value_counts()

road_type
urban      6745
rural      6639
highway    6616
Name: count, dtype: int64

In [53]:
df['cause'].value_counts()

cause
distraction      4026
overspeeding     4025
weather          3997
drunk driving    3978
poor road        3974
Name: count, dtype: int64

In [55]:
pd.crosstab(df['weather'], df['accident_severity'])

accident_severity  fatal  major  minor
weather
clear                992   2017   3681
fog                  995   1975   3663
rain                1000   1996   3681

In [57]:
pd.crosstab(df['road_type'], df['accident_severity'])

accident_severity  fatal  major  minor
road_type
highway              983   1967   3666
rural                965   2014   3660
urban               1039   2007   3699

In [59]:
pd.crosstab(df['cause'], df['accident_severity'])

accident_severity  fatal  major  minor
cause
distraction          542   1244   2240
drunk driving        618   1164   2196
overspeeding         603   1203   2219
poor road            623   1172   2179
weather              601   1205   2191

In [63]:
df['state'].value_counts()

state
Maharashtra    5009
Punjab         2577
Tamil Nadu     2575
West Bengal    2559
Karnataka      2438
Delhi          2433
Telangana      2409
Name: count, dtype: int64

In [65]:
df['city'].value_counts()

city
Chandigarh    2577
Chennai       2575
Kolkata       2559
Pune          2517
Mumbai        2492
Bangalore     2438
Delhi         2433
Hyderabad     2409
Name: count, dtype: int64

In [67]:
df['month'] = df['date'].dt.month_name()

df['month'].value_counts()

month
January      2044
March        2043
February     1865
April        1763
May          1593
August       1588
July         1543
November     1533
December     1525
October      1516
June         1512
September    1475
Name: count, dtype: int64

In [69]:
df.groupby('state')['risk_score'].mean()

state
Delhi          0.437115
Karnataka      0.440217
Maharashtra    0.435097
Punjab         0.441618
Tamil Nadu     0.437573
Telangana      0.439456
West Bengal    0.434584
Name: risk_score, dtype: float64

In [71]:
df.groupby('weather')['risk_score'].mean()

weather
clear    0.236876
fog      0.589123
rain     0.488146
Name: risk_score, dtype: float64

In [73]:
df.to_csv("cleaned_road_accidents.csv", index=False)

In [75]:
df.groupby('state')['risk_score'].mean().sort_values(ascending=False)

state
Punjab         0.441618
Karnataka      0.440217
Telangana      0.439456
Tamil Nadu     0.437573
Delhi          0.437115
Maharashtra    0.435097
West Bengal    0.434584
Name: risk_score, dtype: float64

In [77]:
df.groupby('city')['casualties'].sum().sort_values(ascending=False)

city
Chennai       4567
Kolkata       4508
Pune          4419
Chandigarh    4377
Mumbai        4297
Delhi         4175
Bangalore     4128
Hyderabad     4058
Name: casualties, dtype: int64

In [79]:
df.to_csv("cleaned_road_accidents.csv", index=False)

In [81]:
import os
print(os.getcwd())

C:\Users\USER

In [1]:
import pandas as pd

df = pd.read_csv("cleaned_road_accidents.csv")

sample = df.head(1000)

sample.to_csv("sample_accidents.csv", index=False)